### ISSUE TITLE
Add information about adding peers for ropsten

### ISSUE THREAD

**Issue by kelsos** [Sikorkaio/android-app#8]
Currently the peer list in the application is outdated, thus sync will not start.
Provide a small guide on how to manually update the static-nodes file on Android.

**Comment by LefterisJP** [comment]
Question: Instead of manually asking users to mess with a file in the system is there any way to make this edit from inside the app? If yes it can be put in "Advanced Settings". 

This will probably not be needed in a mainnet deployment but for the testnet, messing with the peers is unfortunately required.

**Comment by kelsos** [comment]
@LefterisJP Yes that can be done I am closing this issue since this was about the guide part and I will open a new one for the implementation of the feature.
